-- AUTO_INCREMENT for table student
ALTER TABLE student
  MODIFY StudentNumber int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- AUTO_INCREMENT for table teacher
ALTER TABLE teacher
  MODIFY TeacherID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- AUTO_INCREMENT for table Teacher_Course
ALTER TABLE Teacher_Course
  MODIFY SeqID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- AUTO_INCREMENT for table Student_Course
ALTER TABLE Student_Course
  MODIFY SeqID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- AUTO_INCREMENT for table Student_Mark
ALTER TABLE Student_Mark
  MODIFY SeqID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- AUTO_INCREMENT for table Department
ALTER TABLE Department
  MODIFY DeptID int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
